declare const _default: {
    getCOSToken: string;
    buildInfo: string;
    installApp: string;
    viewApp: string;
    updateApp: string;
    updateAppInfo: string;
    buildApps: string;
    getByShortcut: string;
    listMy: string;
    setNewestVersion: string;
    cancelNewestVersion: string;
    checkAppIsUpdate: string;
    appGroupListAll: string;
    appGroupView: string;
    feedbackListAll: string;
    feedbackView: string;
    crashListAll: string;
    crashView: string;
    certificateIndex: string;
    deleteApp: string;
};
export default _default;
export declare function getUrl(path: string): string;
